### ISSUE TITLE
No fallback response defined for GET to https://API_URL/api/v1/invite/undefined

### ISSUE THREAD

**Issue by sahibjotsaggu** [wheresrhys/fetch-mock#299] opened 2018-04-13 18:11 UTC
I am trying to mock an API call to `/invite/[INVITE_TOKEN]` but I keep getting `No fallback response defined for GET to https://API_URL/api/v1/invite/undefined`.
```javascript
import React from 'react';
import thunk from 'redux-thunk';
import fetchMock from 'fetch-mock';
import * as actions from 'actions/cardActions';
import * as types from 'actions/cardActions/constants';
import configureMockStore from 'redux-mock-store';

const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

describe('container', () => {
 afterEach(() => {
   fetchMock.reset();
   fetchMock.restore();
 });

 it('creates [ACTION_TYPE] action when fetching [THINGS] has been done', () => {
   fetchMock.getOnce('/invite/[INVITE_TOKEN_HERE]', {
     "token": "INVITE_TOKEN_HERE",
     "space_id": [INTEGER]
   });
 });
});
```

**Comment by wheresrhys** [comment] 2018-04-15 21:24
The error is telling you that `https://API_URL/api/v1/invite/undefined` has not been mocked. So 3 things jump out at me:
- you're not passing `API_URL` into the mock
- you're missing `/api/v1` from the mock
- `INVITE_TOKEN` is undefined in the url, which suggests you're not defining it properly in the test

Closing for now. Please reopen and create a demo repo recreating the problem if it persists

**Closed by wheresrhys** 2018-04-15 21:24 UTC

**Comment by jharris4** [comment] 2019-04-01 02:31
Just FYI I hit this same error, and it seems that it is caused by either not having body or response set in the options. it had nothing to do with the matcher/url.

**Comment by ChetnaGupta** [comment] 2019-06-08 21:21
@jharris4 Can you share the exact code snippet where we need to add body/response in options for reference?

**Comment by jharris4** [comment] 2019-06-09 16:33
@ChetnaGupta sorry, it has been a while since I looked at this, but I can tell you the changes I made to update to the new version:

In most of our tests it was as simple as removing this line:

`sendAsJson: true`

And for one of the tests, I had to replace:

```javascript
response: {
  status: status,
  headers: {
    ['Content-Type']: 'application/json'
  },
  body: '',
  sendAsJson: true
}
```

with just:

`response: status`

**Comment by ChetnaGupta** [comment] 2019-06-11 09:14
Thanks @jharris4
