### ISSUE TITLE
How do I dispatch a action to store with fetch-mock?

### ISSUE THREAD

**Issue by abe6558** [wheresrhys/fetch-mock#316] opened 2018-06-03 23:29 UTC
I need help with testing a redux fetch call with fetch-mock. Function requestPredict() in dashboardActions.js, should fetch api call and then inside resultReady(data) a action should be called. But when I run the test I get a failed test below.
```Expected value to equal:
  [{"type": undefined}, {"data": {"hello": "world"}, "type": undefined}]
Received:
  [{"type": "DASHBOARD_RESULT_LOADING"}, {"result": {"result": {"hello": "world"}}, "type": "DASHBOARD_RESULT_READY"}]

```

```
dashboardActions.js

  function resultReady(json) {
  return {
    type: DASHBOARD_RESULT_READY,
    result: camelizeKeys(json)
    };
   }

 export function requestPredict(subPath, params) {
 let url = `${process.env.API_URL}/predict/${subPath}`;
 const requestParams = {
 method: 'post',
 credentials: 'include',
 body: JSON.stringify(params),
 headers: {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${process.env.API_AUTH_TOKEN}`
  }
 };
 return async (dispatch, getState) => {

 return fetch(url, requestParams)
  .then(response => {
    if (response.status === 200) {
      return response.json();
    } else {
      throw Error(response.statusText);
    }
  })
  .then(data => dispatch(resultReady(data)));
 };
 }

```
```
dashboardActions.test.js

const mockData = { 
  "hello": "world"
}
describe('action creators', () => {

  afterEach(() => {
    fetchMock.reset()
  })

it('should create DASHBOARD_RESULT_READY', () => {
fetchMock.post('*',{ result: { "hello": 'world'} });

const expectedActions = [
  { type: actions.DASHBOARD_RESULT_LOADING },
  { type: actions.DASHBOARD_RESULT_READY, data: mockData }
]

const store = mockStore({
  result: {}
})

return store.dispatch(actions.requestPredict())
  .then((data) => {
    expect(store.getActions()).toEqual(expectedActions)
  })
 })
})
```

**Comment by wheresrhys** [comment] 2018-06-04 20:49
It looks to me like the mock is working fine, but you're assigning things incorrectly. You're expecting

```js
const expectedActions = [
  { type: actions.DASHBOARD_RESULT_LOADING },
  { type: actions.DASHBOARD_RESULT_READY, data: mockData }
]
```
But your code in `resultReady` is assigning the result of the json call to a `result` property, not a `data` property. You also already have a `result` property in the data defined in the mock, but `resultReady` also assigns to a `result` property.

I'm not sure what the desired behaviour actually is, but if you were to change `data` to `result` in `expectedActions` and use `fetchMock.post('*',{ "hello": 'world'});` then that bit of the test would past. 

The fact that the tests are failing because of `type: undefined` too suggests that there's something else wrong somewhere too.

Closing this issue as I don't think the problem is a bug in fetch-mock. Good luck finding the issue 😃

**Closed by wheresrhys** 2018-06-04 20:49 UTC

**Comment by abe6558** [comment] 2018-06-04 21:53
Thanks it resolved one of the issues! 
Shouldnt resultReady() dispatch 'DASHBOARD_RESULT_READY'? Im getting this error: 

```Expected value to equal:
  [{"type": undefined}, {"result": {"hello": "world"}, "type": undefined}]
Received:
  [{"type": "DASHBOARD_RESULT_LOADING"}, {"result": {"hello": "world"}, "type": "DASHBOARD_RESULT_READY"}]```

**Comment by abe6558** [comment] 2018-06-04 21:55
Im trying to test it similar with Redux docs.
[https://redux.js.org/recipes/writing-tests](url)
