### ISSUE TITLE
support for synchronous testing 

### ISSUE THREAD

**Issue by nish1013** [wheresrhys/fetch-mock#164] opened 2017-01-25 17:26 UTC
Is it possible to mock synchronously ?

**Comment by wheresrhys** [comment] 2017-01-25 23:55
duplicate of https://github.com/wheresrhys/fetch-mock/issues/97.

Synchronous testing isn't supported, and is probably a bad idea, because fetch is an inherently async api, so any mock that allows synchronisity is likely to be a poor imitation of production code.

**Comment by wheresrhys** [comment] 2017-01-25 23:56
Thanks for raising this though. When fetch-mock gets better docs I'll try to remember to add this to some sort of FAQ

**Closed by wheresrhys** 2017-01-25 23:55 UTC
