### ISSUE TITLE
Getting an empty array as a response

### ISSUE THREAD

**Issue by patrickliechty** [wheresrhys/fetch-mock#304] opened 2018-05-03 20:54 UTC
I am running the code in a unit test in Web Component Tester

//Load fetch-mock
  <script src="../../../../node_modules/fetch-mock/es5/client-bundle.js"></script>

//Unit test
```
      fetchMock.get("https://beta.familysearch.org/platform/vocab/lists/104254.json", {"first_name": "John", "last_name": "Smith"})
```

//Code that uses fetch.  Using fetch in Chrome browser
```
    return fetch(url).then((list) => {
        return this.parseAuthorityList(list, type)
      });
```
//Back in unit test:
```
     fetchMock.called("https://beta.familysearch.org/platform/vocab/lists/104254.json") //returns true
```
The response I get back is an empty array

**Comment by patrickliechty** [comment] 2018-05-10 21:45
Ok I will try that.  Was that in the documentation?  I read a lot of it and don't remember reading that or seeing that in the examples.

**Comment by wheresrhys** [comment] 2018-05-12 14:43
That's part of the fetch api, so out of scope for me to document. The problem is with your use of fetch, not your use of fetch-mock. Here are a couple of great articles:

https://developers.google.com/web/updates/2015/03/introduction-to-fetch
https://jakearchibald.com/2015/thats-so-fetch/

**Closed by wheresrhys** 2018-05-12 14:43 UTC
