### ISSUE TITLE
Why does fetchMock.get() take so long?

### ISSUE THREAD

**Issue by mjstromberg** [wheresrhys/fetch-mock#205] opened 2017-07-25 23:17 UTC
I'm using fetchMock.get() in a simple case to test that my React thunk is dispatching the correct actions. If I'm never going across a network boundary, why does my test take so long? I've seen it take upwards of 180ms!

I know that this test isn't in total isolation, but I was hoping there was an obvious answer (e.g. There is a randomized delay built in that I'm not aware of, etc.). Any help is greatly appreciated!

```
import { expect } from 'chai';
import thunk from 'redux-thunk';
import configureMockStore from 'redux-mock-store';
import fetchMock from 'fetch-mock';
import fetchTilesData from '../thunks';
import actionTypes from '../actionTypes';
import { sampleResponseData } from '../../../tiles/mockedData/sampleResponseData';

describe('fetchTilesData', () => {
    afterEach(() => { fetchMock.restore(); });

    it('should dispatch the correct actions', () => {
      const middlewares = [thunk];
      const mockStore = configureMockStore(middlewares);
      const expectedActions = [
        { type: actionTypes.MGR_TILES_FETCH_START },
        { type: actionTypes.MGR_TILES_FETCH_SUCCESS, payload: sampleResponseData }
      ];
      const store = mockStore({
        dashboard: {
          filters: {
            topFilters: []
          },
          manager: {
            tiles: {
              isLoadingTiles: true,
              portfolioTotals: {
                closed: 0,
                'non-critical': 0,
                critical: 0
              },
              portfolios: [],
              tilesSortOrderIndex: 0
            }
          }
        }
      });

      fetchMock.get('*', sampleResponseData);

      return store.dispatch(fetchTilesData()).then(() => {
        expect(store.getActions()).to.eql(expectedActions);
      });
    });
  });
```

**Comment by wheresrhys** [comment] 2017-07-27 23:03
Can't think what it could be. There are no artificial delays built in (promises resolve as soon as possible). I use fetch-mock in test suites most days and have never experienced this. All I can suggest is that there is a performance bug in your code somewhere. Have you tried profiling your production code?

Closing for now, but happy to look at it again if you find evidence the problem is in fetch-mock.

**Closed by wheresrhys** 2017-07-27 23:03 UTC

**Comment by mjstromberg** [comment] 2017-07-27 23:08
@wheresrhys , thanks for looking into this; I appreciate it.

The thunk above isn't doing anything special, so I'm now inclined to think it's the redux-mock-store library that is causing the delay because there isn't anything else in the stack that would/should cause this delay.

Thanks again!
