### ISSUE TITLE
Matching Request does not work when using electrode-archetype-react-app

### ISSUE THREAD

**Issue by jshado1** [wheresrhys/fetch-mock#243] opened 2018-01-11 13:14 UTC
I read through the troubleshooting guide and tried all of the suggestions, but no dice. It was also pretty difficult to grok with Examples being `//todo`.

name | version
--- | ---
node | `6.10.0`
npm | `3.10.10`
isomorphic-fetch | `2.2.1`
fetch-mock | `5.13.1`
bluebird | `3.5.1`

In my `karma.conf.js` I have
```js
require('isomorphic-fetch');
var fetchMock = require('fetch-mock');
fetchMock.catch(function() { // I tried pretty much every variation of catch() and mock()
    console.log('\n\nFETCH MOCKER:: CATCH\n\n');

    return {};
});

module.exports = function (config, settings){
    // …

    config.set(settings)
}
```

When I kick off Karma, WebPack compiles all of the modules and then hangs until Karma hits its timeout and aborts. No specs are executed.

Note that one of the compiled modules triggers a fetch request immediately.

If I try to provide bluebird to fetch-mocker, as recommended in the [API Documentation](http://www.wheresrhys.co.uk/fetch-mock/api#config), I get the following error

```js
var Promise = require('bluebird');
var fetchMock = require('fetch-mock');

Object.assign(fetchMock.config, { Promise: Promise });
```
```
TypeError: Cannot convert undefined or null to object
```

`fetchMock` and `Promise` are defined, but `fetchMock.config` is not.

fetchMock has the following (according to `util.inspect`:
```js
{
    routes: [],
    _calls:
    {},
    _matchedCalls: [],
    _unmatchedCalls: [],
    _holdingPromises: [],
    fetchMock: [Function: bound],
    restore: [Function: bound],
    reset: [Function: bound]
}
```

**Comment by wheresrhys** [comment] 2018-01-12 23:26
Could you share a repo with a minimal test case I can clone, install and run please. It may be something related to webpack

**Comment by jshado1** [comment] 2018-01-13 10:13
Sure, I'll put one together.

**Comment by jshado1** [comment] 2018-01-13 12:45
Soooo the minimal test case runs just fine 😓

`fetchMock.config` still doesn't exist, but the `fetchMock.catch()` does execute.

I know which line in the actual code is the start of the problem; it's the root of a very long, branching chain of promises, so I'm guessing one of those branches doesn't maintain the chaining properly, causing the spec runner to not get signalled when it settles.

Thanks and sorry for taking your time.

**Comment by jshado1** [comment] 2018-01-15 17:23
I spoke too soon: It turns out my minimal test was overly minimal. One problem occurs when an exception is thrown and subsequently swallowed by fetch-mock. I haven't been able to narrow down the hanging yet, but when an exception would have been thrown, fetch-mock fails altogether (`fetchMock.catch()` does not execute).

Please see https://github.com/jshado1/fetch-mock-test. The first commit works fine. The second commit adds `const req = new Request();` (which would cause a TypeError due to missing arguments) and is broken (and no error is thrown).

**Comment by wheresrhys** [comment] 2018-01-17 21:10
Do I understand correctly that the problem is that when fetch is called with a `Request` object, function matchers that are aimed at inspecting the request are passed the url, not the full `Request`?

Have you tried the latest beta (6.0.0-beta.9). Someone else reported a similar bug a week or two or go, and it should be fixed

**Comment by jshado1** [comment] 2018-01-17 21:39
No. For this particular issue, anything invalid in relation to the Request (and I think also Headers) APIs causes a silent failure (fetch-mock swallows the thrown error and then does nothing else). I see there are some Promises used under the hood, so perhaps the error is getting thrown within one of those and there isn't a `promise.catch()` or if there is a `promise.catch()`, it isn't logging/exposing the error.

What you described above sounds like #44, which I also commented on.

Off the top of my head, I don't remember which beta I was using (I wanna say 7); I'll check tomorrow morning and try b9 if it wasn't that already.

**Comment by jshado1** [comment] 2018-01-18 14:45
@wheresrhys I just tried `6.0.0-beta.9` and neither issue is fixed in it.

**Comment by wheresrhys** [comment] 2018-01-19 22:29
As this was broken in v5 too I'm not going to prioritise fixing this I'm sorry. My guess is that the test setup you're using falls victim to something similar to the issues that have happened in the past around webpack and requiring (there are a few notes in the troubleshooting guide around this). There's a lot of stuff going on in `electrode-archetype-react-app` and I can't justify spending any more time investigating an issue which is probably more to to with that toolchain than it is with fetch-mock. 

I suggest trying to raise the issue you've been having with the electrode community and see if there are some changes that can be made there. I'll keep this issue open with a changed title so that others can help solve it if they come across it, and I hope someone is able to fix it.

**Comment by jshado1** [comment] 2018-01-19 22:39
Does matching a `Request` work without all the extra bits from Electrode? I don't see any code that would make it work; the code that previously made it work appears to be gone.

**Comment by jshado1** [comment] 2018-01-19 22:46
Also I offered to try to fix it for you

**Comment by wheresrhys** [comment] 2018-01-20 09:52
There is a passing test for exactly the behaviour that's failing for you https://github.com/wheresrhys/fetch-mock/blob/master/test/specs/routing.test.js#L536, which passes in the 3 different environments the tests are run in. I'm happy to accept a PR fixing the issue, but I'd be surprised if the problem doesn't lie outside of fetch-mock

**Comment by jshado1** [comment] 2018-01-22 14:56
@wheresrhys, the test you linked doesn't authentically verify `fetch` being called with a `Request` instance. I added [one](https://github.com/jshado1/fetch-mock/compare/v6...jshado1:global-fetch-with-req-inst?expand=1) in my fork of this repo that I think does it more authentically, and it results in basically the same output as my original test repo.

The test passes because sinon.stub is behaving properly:

```js
originalFetch = theGlobal.fetch = sinon.stub().returns(Promise.resolve('dummy'));
```
```js
await theGlobal.fetch(req);

console.log(util.inspect(fetchMock._calls, {depth: 5}));
console.log(util.inspect(fetchMock.calls(), {depth: 5}));
console.log(util.inspect(fetchMock.calls(req), {depth: 5}));

expect(originalFetch).calledWith(req);
```

As far as I can see, there's no useful data in fetchMock's record of the call:

```
WARN: 'Unmatched GET to [object Request]'
LOG: '{}'
LOG: '[ [ {}, undefined, unmatched: true ] ]'
LOG: '[ [ {}, undefined, unmatched: true ] ]'
```

**Comment by wheresrhys** [comment] 2018-01-22 22:38
`util.inspect` doesn't necessary surface properties set on the prototype, or accessed via getters. Logging exact properties works: `console.log(fetchMock.calls()[0][0].url); // 'http://a.com/'`

I'm going to close this issue. Me pointing you in the direction of electrode is trying to save us both some time. Please reopen if, _after_ digging through electrode, you trace the problem back to fetch-mock. Best of luck.

**Closed by wheresrhys** 2018-01-22 22:38 UTC
Labels: bug, help wanted
